apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJjbTl0WVhGM1pYSjBlVHBuYUhCZlJtcG9ZbWRqY0hGTFUxQldORU5PTXpaa1JYVTJiV3RHWlRRd01HeDRORkJyVkcxVSIKICAgIH0KICB9LAogICJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAogICJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4Igp9
type: kubernetes.io/dockerconfigjson
